name: Build EBook and Website

on:
  push:
    branches:
      - main
    paths:
      - '**/*.md'
      - '**/*.jpg'
      - '**/*.zsh'
      - '**/*.css'
      - 'template.html'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick calibre pandoc zsh

      - name: Install FiraCode fonts
        run: |
          mkdir -p ~/.local/share/fonts
          curl -L -o /tmp/FiraCode.zip https://github.com/tonsky/FiraCode/releases/download/5.2/Fira_Code_v5.2.zip
          if [ $? -ne 0 ]; then echo "Error downloading FiraCode.zip"; exit 1; fi
          unzip /tmp/FiraCode.zip -d /tmp/FiraCode
          if [ $? -ne 0 ]; then echo "Error unzipping FiraCode.zip"; exit 1; fi
          cp /tmp/FiraCode/ttf/*.ttf ~/.local/share/fonts/
          fc-cache -f -v

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Run EPUB build script
        env:
          GITHUB_ACTIONS: true
        run: zsh ./build-ebook.zsh

      - name: Run website build script
        run: zsh ./build-website.zsh

      - name: Rename EPUB file
        run: |
          mkdir -p website/downloads
          mv LUSBSE.epub website/downloads/latest.epub

      - name: Display build.md content
        run: cat build.md

      - name: Display tmp_cover.jpg details
        run: |
          file tmp_cover.jpg
          ls -lh tmp_cover.jpg

      - name: Commit and push changes
        run: |
          git add website/downloads/latest.epub website/sutras/**/*.html website/index.html
          git commit -m "Update EPUB and HTML files"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
